services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    profiles:
      - docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mysql:
    image: mysql:8.4.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=hackathon
    ports:
      - 3306:3306
