services:
  app:
    image: azul/zulu-openjdk:17.0.9
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    profiles:
      - docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "chmod +x ./gradlew && ./gradlew bootJar -Pprofile=docker && java -jar build/libs/Backend-0.0.1-SNAPSHOT.jar"

  mysql:
    image: mysql:8.4.0
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=share_me
    ports:
      - "3306:3306"
