services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_PROFILE: dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    profiles:
      - dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  mysql:
    image: mysql:8.4.0
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=share_me
    ports:
      - "3306:3306"
