INSERT INTO `events` (`event_id`, `created_at`, `updated_at`)
VALUES (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), NOW(), NOW());

INSERT INTO `accounts` (`kakao_oauth_id`, `name`, `email`, `initial_role_granted_flag`, `linkedin_url`, `github_url`,
                        `instagram_url`, `created_at`, `updated_at`)
VALUES (1, 'User 1', 'user1@example.com', TRUE, 'https://linkedin.com/in/user1', NULL, 'https://instagram.com/user1',
        NOW(), NOW()),
       (2, 'User 2', 'user2@example.com', TRUE, NULL, 'https://github.com/user2', NULL, NOW(), NOW()),
       (3, 'User 3', 'user3@example.com', TRUE, 'https://linkedin.com/in/user3', 'https://github.com/user3',
        'https://instagram.com/user3', NOW(), NOW()),
       (4, 'User 4', 'user4@example.com', TRUE, NULL, NULL, 'https://instagram.com/user4', NOW(), NOW()),
       (5, 'User 5', 'user5@example.com', TRUE, 'https://linkedin.com/in/user5', NULL, NULL, NOW(), NOW()),
       (6, 'User 6', 'user6@example.com', TRUE, NULL, 'https://github.com/user6', 'https://instagram.com/user6', NOW(),
        NOW()),
       (7, 'User 7', 'user7@example.com', TRUE, 'https://linkedin.com/in/user7', 'https://github.com/user7', NULL,
        NOW(), NOW()),
       (8, 'User 8', 'user8@example.com', TRUE, NULL, NULL, NULL, NOW(), NOW()),
       (9, 'User 9', 'user9@example.com', TRUE, 'https://linkedin.com/in/user9', NULL, 'https://instagram.com/user9',
        NOW(), NOW()),
       (10, 'User 10', 'user10@example.com', TRUE, NULL, 'https://github.com/user10', NULL, NOW(), NOW()),
       (11, 'User 11', 'user11@example.com', TRUE, 'https://linkedin.com/in/user11', 'https://github.com/user11',
        'https://instagram.com/user11', NOW(), NOW()),
       (12, 'User 12', 'user12@example.com', TRUE, NULL, NULL, 'https://instagram.com/user12', NOW(), NOW()),
       (13, 'User 13', 'user13@example.com', TRUE, 'https://linkedin.com/in/user13', NULL, NULL, NOW(), NOW()),
       (14, 'User 14', 'user14@example.com', TRUE, NULL, 'https://github.com/user14', 'https://instagram.com/user14',
        NOW(), NOW()),
       (15, 'User 15', 'user15@example.com', TRUE, 'https://linkedin.com/in/user15', 'https://github.com/user15', NULL,
        NOW(), NOW()),
       (16, 'User 16', 'user16@example.com', TRUE, NULL, NULL, NULL, NOW(), NOW()),
       (17, 'User 17', 'user17@example.com', TRUE, 'https://linkedin.com/in/user17', NULL,
        'https://instagram.com/user17', NOW(), NOW()),
       (18, 'User 18', 'user18@example.com', TRUE, NULL, 'https://github.com/user18', NULL, NOW(), NOW()),
       (19, 'User 19', 'user19@example.com', TRUE, 'https://linkedin.com/in/user19', 'https://github.com/user19',
        'https://instagram.com/user19', NOW(), NOW()),
       (20, 'User 20', 'user20@example.com', TRUE, NULL, NULL, 'https://instagram.com/user20', NOW(), NOW()),
       (21, 'User 21', 'user21@example.com', TRUE, 'https://linkedin.com/in/user21', NULL, NULL, NOW(), NOW()),
       (22, 'User 22', 'user22@example.com', TRUE, NULL, 'https://github.com/user22', 'https://instagram.com/user22',
        NOW(), NOW()),
       (23, 'User 23', 'user23@example.com', TRUE, 'https://linkedin.com/in/user23', 'https://github.com/user23', NULL,
        NOW(), NOW()),
       (24, 'User 24', 'user24@example.com', TRUE, NULL, NULL, NULL, NOW(), NOW()),
       (25, 'User 25', 'user25@example.com', TRUE, 'https://linkedin.com/in/user25', NULL,
        'https://instagram.com/user25', NOW(), NOW()),
       (26, 'User 26', 'user26@example.com', TRUE, NULL, 'https://github.com/user26', NULL, NOW(), NOW()),
       (27, 'User 27', 'user27@example.com', TRUE, 'https://linkedin.com/in/user27', 'https://github.com/user27',
        'https://instagram.com/user27', NOW(), NOW()),
       (28, 'User 28', 'user28@example.com', TRUE, NULL, NULL, 'https://instagram.com/user28', NOW(), NOW()),
       (29, 'User 29', 'user29@example.com', TRUE, 'https://linkedin.com/in/user29', NULL, NULL, NOW(), NOW()),
       (30, 'User 30', 'user30@example.com', TRUE, NULL, 'https://github.com/user30', 'https://instagram.com/user30',
        NOW(), NOW()),
       (31, 'User 31', 'user31@example.com', TRUE, 'https://linkedin.com/in/user31', 'https://github.com/user31', NULL,
        NOW(), NOW()),
       (32, 'User 32', 'user32@example.com', TRUE, NULL, NULL, NULL, NOW(), NOW()),
       (33, 'User 33', 'user33@example.com', TRUE, 'https://linkedin.com/in/user33', NULL,
        'https://instagram.com/user33', NOW(), NOW()),
       (34, 'User 34', 'user34@example.com', TRUE, NULL, 'https://github.com/user34', NULL, NOW(), NOW()),
       (35, 'User 35', 'user35@example.com', TRUE, 'https://linkedin.com/in/user35', 'https://github.com/user35',
        'https://instagram.com/user35', NOW(), NOW()),
       (36, 'User 36', 'user36@example.com', TRUE, NULL, NULL, 'https://instagram.com/user36', NOW(), NOW()),
       (37, 'User 37', 'user37@example.com', TRUE, 'https://linkedin.com/in/user37', NULL, NULL, NOW(), NOW()),
       (38, 'User 38', 'user38@example.com', TRUE, NULL, 'https://github.com/user38', 'https://instagram.com/user38',
        NOW(), NOW()),
       (39, 'User 39', 'user39@example.com', TRUE, 'https://linkedin.com/in/user39', 'https://github.com/user39', NULL,
        NOW(), NOW()),
       (40, 'User 40', 'user40@example.com', TRUE, NULL, NULL, NULL, NOW(), NOW()),
       (41, 'User 41', 'user41@example.com', TRUE, 'https://linkedin.com/in/user41', NULL,
        'https://instagram.com/user41', NOW(), NOW()),
       (42, 'User 42', 'user42@example.com', TRUE, NULL, 'https://github.com/user42', NULL, NOW(), NOW()),
       (43, 'User 43', 'user43@example.com', TRUE, 'https://linkedin.com/in/user43', 'https://github.com/user43',
        'https://instagram.com/user43', NOW(), NOW()),
       (44, 'User 44', 'user44@example.com', TRUE, NULL, NULL, 'https://instagram.com/user44', NOW(), NOW()),
       (45, 'User 45', 'user45@example.com', TRUE, 'https://linkedin.com/in/user45', NULL, NULL, NOW(), NOW()),
       (46, 'User 46', 'user46@example.com', TRUE, NULL, 'https://github.com/user46', 'https://instagram.com/user46',
        NOW(), NOW()),
       (47, 'User 47', 'user47@example.com', TRUE, 'https://linkedin.com/in/user47', 'https://github.com/user47', NULL,
        NOW(), NOW()),
       (48, 'User 48', 'user48@example.com', TRUE, NULL, NULL, NULL, NOW(), NOW()),
       (49, 'User 49', 'user49@example.com', TRUE, 'https://linkedin.com/in/user49', NULL,
        'https://instagram.com/user49', NOW(), NOW()),
       (50, 'User 50', 'user50@example.com', TRUE, NULL, 'https://github.com/user50', NULL, NOW(), NOW()),
       (51, 'User 51', 'user51@example.com', TRUE, 'https://linkedin.com/in/user51', 'https://github.com/user51',
        'https://instagram.com/user51', NOW(), NOW()),
       (52, 'User 52', 'user52@example.com', TRUE, NULL, NULL, 'https://instagram.com/user52', NOW(), NOW()),
       (53, 'User 53', 'user53@example.com', TRUE, 'https://linkedin.com/in/user53', NULL, NULL, NOW(), NOW()),
       (54, 'User 54', 'user54@example.com', TRUE, NULL, 'https://github.com/user54', 'https://instagram.com/user54',
        NOW(), NOW()),
       (55, 'User 55', 'user55@example.com', TRUE, 'https://linkedin.com/in/user55', 'https://github.com/user55', NULL,
        NOW(), NOW()),
       (56, 'User 56', 'user56@example.com', TRUE, NULL, NULL, NULL, NOW(), NOW()),
       (57, 'User 57', 'user57@example.com', TRUE, 'https://linkedin.com/in/user57', NULL,
        'https://instagram.com/user57', NOW(), NOW()),
       (58, 'User 58', 'user58@example.com', TRUE, NULL, 'https://github.com/user58', NULL, NOW(), NOW()),
       (59, 'User 59', 'user59@example.com', TRUE, 'https://linkedin.com/in/user59', 'https://github.com/user59',
        'https://instagram.com/user59', NOW(), NOW()),
       (60, 'User 60', 'user60@example.com', TRUE, NULL, NULL, 'https://instagram.com/user60', NOW(), NOW());

-- profiles 테이블 DML (60개 레코드)
INSERT INTO `profiles` (`event_id`, `account_id`, `pin_number`, `icon_number`, `introduce`, `proudest_experience`,
                        `tough_experience`, `created_at`, `updated_at`)
VALUES (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 1, 1001, 5, '안녕하세요, User 1입니다. 새로운 도전을 즐깁니다.',
        '혁신적인 프로젝트를 성공적으로 이끌었습니다.', '예상치 못한 기술적 난관에 부딪혔을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 2, 1002, 12, '항상 배우고 성장하는 것을 목표로 합니다.',
        '복잡한 문제를 효율적으로 해결했습니다.', '팀원 간의 의견 차이를 조율하는 과정', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 3, 1003, 2, '긍정적인 에너지로 주변을 밝힙니다.', '고객 만족도를 크게 향상시킨 경험',
        '시간 제약이 있는 프로젝트를 진행할 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 4, 1004, 9, '새로운 아이디어를 탐구하는 것을 좋아합니다.',
        '새로운 시장 기회를 발굴했습니다.', '예상치 못한 팀원 이탈로 인한 공백', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 5, 1005, 7, '데이터 분석을 통해 가치를 창출합니다.',
        '데이터 기반 의사결정으로 성과를 냈습니다.', '대규모 데이터 처리 과정에서의 오류', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 6, 1006, 1, '사용자 경험을 최우선으로 생각합니다.',
        '사용자 피드백을 반영하여 제품을 개선했습니다.', '사용자 요구사항을 정확히 파악하기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 7, 1007, 11, '협업과 소통을 중요하게 생각합니다.', '다국적 팀과 성공적으로 협력했습니다.',
        '문화적 차이로 인한 의사소통 문제', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 8, 1008, 3, '지속적인 학습을 통해 역량을 강화합니다.',
        '새로운 기술을 빠르게 습득하여 적용했습니다.', '새로운 분야에 대한 지식 부족', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 9, 1009, 8, '문제 해결에 대한 열정이 있습니다.', '복잡한 버그를 찾아내어 해결했습니다.',
        '예상치 못한 시스템 장애 발생', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 10, 1010, 6, '창의적인 아이디어로 가치를 더합니다.',
        '독창적인 마케팅 캠페인을 기획했습니다.', '아이디어가 현실화되기까지의 난관', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 11, 1011, 4, '변화에 빠르게 적응하는 능력이 있습니다.',
        '급변하는 시장에 맞춰 전략을 수정했습니다.', '불확실한 상황에서의 의사결정', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 12, 1012, 10, '꼼꼼하고 체계적인 업무 처리를 지향합니다.',
        '정확한 보고서 작성으로 신뢰를 얻었습니다.', '세부적인 부분에서 발생하는 실수', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 13, 1013, 1, '도전적인 과제를 즐기며 성장합니다.', '어려운 목표를 설정하고 달성했습니다.',
        '목표 달성 과정에서 겪는 좌절감', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 14, 1014, 7, '긍정적인 태도로 팀에 기여합니다.', '팀의 사기를 높이는 데 기여했습니다.',
        '팀 내 갈등 상황을 중재할 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 15, 1015, 3, '효율적인 프로세스 개선에 관심이 많습니다.',
        '업무 프로세스를 개선하여 생산성을 높였습니다.', '기존 시스템을 변경하는 데 대한 저항', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 16, 1016, 12, '새로운 기술 트렌드를 주시합니다.',
        '최신 기술을 도입하여 경쟁력을 확보했습니다.', '새로운 기술 도입에 필요한 학습 시간', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 17, 1017, 5, '고객의 목소리에 귀 기울입니다.',
        '고객의 니즈를 파악하여 맞춤형 솔루션을 제공했습니다.', '고객의 불만을 해결하기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 18, 1018, 9, '명확하고 간결한 의사소통을 추구합니다.',
        '복잡한 내용을 쉽게 설명하여 이해를 도왔습니다.', '의도와 다르게 전달된 메시지', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 19, 1019, 2, '자기 주도적으로 업무를 수행합니다.',
        '주어진 업무 외에 추가적인 개선 사항을 제안했습니다.', '예상치 못한 외부 요인으로 인한 계획 변경', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 20, 1020, 10, '데이터 시각화에 강점이 있습니다.',
        '복잡한 데이터를 시각적으로 명확하게 표현했습니다.', '데이터의 양이 너무 많아 시각화가 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 21, 1021, 8, '글로벌 환경에서 일하는 것을 선호합니다.',
        '다양한 문화권의 사람들과 협력했습니다.', '언어 장벽으로 인한 의사소통의 어려움', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 22, 1022, 6, '지속적인 피드백을 통해 발전합니다.',
        '피드백을 적극적으로 수용하여 업무에 반영했습니다.', '건설적인 비판을 받아들이기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 23, 1023, 4, '새로운 지식을 습득하는 것에 즐거움을 느낍니다.',
        '새로운 분야의 전문 지식을 습득했습니다.', '방대한 양의 정보를 소화해야 할 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 24, 1024, 11, '위기 상황에서 침착함을 유지합니다.',
        '긴급 상황에서 효과적으로 대응했습니다.', '예상치 못한 위기 상황에 대한 책임감', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 25, 1025, 1, '세심한 관찰력으로 디테일을 놓치지 않습니다.',
        '작은 오류를 발견하여 큰 문제를 방지했습니다.', '반복적이고 지루한 작업', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 26, 1026, 7, '긍정적인 사고로 난관을 극복합니다.',
        '어려운 상황에서도 긍정적인 태도를 유지했습니다.', '개인의 노력만으로는 해결하기 어려운 문제', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 27, 1027, 3, '다양한 관점에서 문제를 분석합니다.',
        '여러 각도에서 문제를 분석하여 최적의 해결책을 찾았습니다.', '정보가 부족한 상황에서의 의사결정', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 28, 1028, 12, '목표 지향적인 태도로 업무에 임합니다.',
        '명확한 목표를 설정하고 달성하기 위해 노력했습니다.', '목표 달성에 필요한 자원 부족', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 29, 1029, 5, '새로운 환경에 빠르게 적응합니다.',
        '낯선 환경에서도 빠르게 적응하여 성과를 냈습니다.', '새로운 환경에서의 문화적 차이', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 30, 1030, 9, '뛰어난 커뮤니케이션 능력을 가지고 있습니다.',
        '복잡한 아이디어를 명확하게 전달했습니다.', '오해로 인한 갈등 발생', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 31, 1031, 2, '문제 해결에 대한 끈기가 있습니다.',
        '수많은 시행착오 끝에 문제를 해결했습니다.', '반복되는 실패로 인한 좌절', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 32, 1032, 10, '팀워크를 통해 시너지를 창출합니다.',
        '팀원들과 협력하여 큰 성과를 달성했습니다.', '팀원 간의 협력 부족', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 33, 1033, 8, '빠른 학습 능력을 보유하고 있습니다.',
        '새로운 도구를 빠르게 익혀 업무에 적용했습니다.', '새로운 학습에 필요한 시간 부족', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 34, 1034, 6, '혁신적인 아이디어를 제안합니다.',
        '기존 방식에 대한 새로운 접근을 시도했습니다.', '아이디어가 받아들여지지 않았을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 35, 1035, 4, '스트레스 상황에서도 평정심을 유지합니다.',
        '압박감 속에서도 침착하게 업무를 처리했습니다.', '과도한 업무량으로 인한 압박', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 36, 1036, 11, '세부 사항에 대한 높은 이해도를 가지고 있습니다.',
        '복잡한 시스템의 세부 사항을 완벽히 이해했습니다.', '정보의 양이 너무 많아 이해하기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 37, 1037, 1, '능동적으로 업무에 참여합니다.',
        '주어진 역할 이상으로 적극적으로 기여했습니다.', '의사 결정 과정에서 소외감을 느꼈을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 38, 1038, 7, '긍정적인 영향력을 행사합니다.', '동료들에게 긍정적인 영향을 미쳤습니다.',
        '부정적인 분위기 속에서 긍정적인 태도를 유지하기', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 39, 1039, 3, '분석적 사고를 통해 문제를 해결합니다.',
        '복잡한 데이터를 분석하여 핵심 문제를 파악했습니다.', '데이터가 불충분하거나 신뢰할 수 없을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 40, 1040, 12, '시간 관리 능력이 뛰어납니다.',
        '여러 프로젝트를 동시에 효율적으로 관리했습니다.', '예상치 못한 일정 변경으로 인한 혼란', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 41, 1041, 5, '뛰어난 적응력으로 변화에 대응합니다.',
        '예상치 못한 상황에 유연하게 대처했습니다.', '변화에 대한 저항에 직면했을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 42, 1042, 9, '창의적인 문제 해결 능력을 갖추고 있습니다.',
        '기존의 틀을 벗어나 새로운 해결책을 제시했습니다.', '아이디어가 현실적으로 구현하기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 43, 1043, 2, '강한 책임감으로 업무를 완수합니다.',
        '주어진 업무에 대해 끝까지 책임지고 완수했습니다.', '책임의 범위가 모호했을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 44, 1044, 10, '데이터 기반의 의사결정을 선호합니다.',
        '데이터를 활용하여 합리적인 의사결정을 내렸습니다.', '데이터 해석에 오류가 있었을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 45, 1045, 8, '효과적인 프레젠테이션 능력을 보유합니다.',
        '복잡한 내용을 쉽게 전달하여 청중을 설득했습니다.', '청중의 반응이 예상과 달랐을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 46, 1046, 6, '끈기 있는 노력으로 목표를 달성합니다.',
        '어려운 상황에서도 포기하지 않고 목표를 달성했습니다.', '노력에 비해 성과가 미미했을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 47, 1047, 4, '다양한 사람들과의 관계 형성에 능숙합니다.',
        '새로운 사람들과 쉽게 관계를 맺고 협력했습니다.', '관계에서 오해가 발생했을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 48, 1048, 11, '빠른 실행력을 통해 성과를 만듭니다.',
        '아이디어를 빠르게 실행하여 결과를 도출했습니다.', '실행 과정에서 예상치 못한 문제 발생', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 49, 1049, 1, '문제의 본질을 파악하는 데 능숙합니다.',
        '표면적인 문제 뒤에 숨겨진 근본 원인을 찾아냈습니다.', '문제의 원인을 찾기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 50, 1050, 7, '긍정적인 태도로 팀의 분위기를 이끌어갑니다.',
        '팀원들에게 긍정적인 에너지를 전달했습니다.', '팀 내 부정적인 분위기를 바꾸기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 51, 1051, 3, '복잡한 시스템을 이해하고 분석합니다.',
        '복잡한 시스템의 구조를 파악하고 개선점을 제안했습니다.', '시스템의 복잡성으로 인한 이해의 어려움', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 52, 1052, 12, '명확한 목표 설정과 달성 능력이 있습니다.',
        '구체적인 목표를 설정하고 계획적으로 달성했습니다.', '목표 달성에 대한 외부의 방해', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 53, 1053, 5, '새로운 기술을 배우는 데 열정적입니다.',
        '최신 기술 동향을 파악하고 학습했습니다.', '새로운 기술의 복잡성으로 인한 학습의 어려움', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 54, 1054, 9, '효과적인 팀 빌딩에 기여합니다.',
        '팀원들 간의 유대감을 강화하고 협력을 이끌어냈습니다.', '팀 내 갈등을 해결하기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 55, 1055, 2, '강한 추진력으로 프로젝트를 이끌어갑니다.',
        '어려운 프로젝트를 성공적으로 완수했습니다.', '프로젝트 진행 중 예상치 못한 장애물', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 56, 1056, 10, '데이터를 기반으로 인사이트를 도출합니다.',
        '방대한 데이터에서 의미 있는 인사이트를 발견했습니다.', '데이터의 품질이 낮아 분석이 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 57, 1057, 8, '뛰어난 협상 능력을 가지고 있습니다.',
        '상대방과의 협상을 통해 긍정적인 결과를 얻었습니다.', '협상 과정에서 의견 차이가 컸을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 58, 1058, 6, '위기 관리 능력이 뛰어납니다.',
        '예상치 못한 위기 상황에 대한 효과적인 대응 계획을 수립했습니다.', '위기 상황에서 정보가 부족했을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 59, 1059, 4, '창의적인 사고로 새로운 가치를 창출합니다.',
        '기존에 없던 새로운 제품이나 서비스를 개발했습니다.', '아이디어를 상업적으로 성공시키기 어려웠을 때', NOW(), NOW()),
       (UUID_TO_BIN('a81bc81b-dead-4e5d-abff-90865d1e13b1'), 60, 1060, 11, '지속적인 개선을 통해 완벽을 추구합니다.',
        '반복적인 개선 작업을 통해 제품의 완성도를 높였습니다.', '개선 과정에서 발생하는 예상치 못한 문제', NOW(), NOW());
