on:
  push:
    branches:
      - chore/connection

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  GAR_LOCATION: asia-northeast3 # Artifact Registry, 인스턴스 리전
  REPOSITORY: shareme-docker
  IMAGE_NAME: shareme-backend
  INSTANCE_GROUP_NAME: shareme-instance-group

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # OIDC 인증을 위해 필수

    steps:
      - name: repository 로드
        uses: actions/checkout@v4

      - name: 카카오 설정 로드
        run: echo "${{ secrets.KAKAO_PROPERTIES }}" > ./src/main/resources/application-kakao.properties

      - name: db 설정 로드
        run: echo "${{ secrets.PROD_PROPERTIES }}" > ./src/main/resources/application-prod.properties

      - name: Set up JDK 17 (Azul Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 테스트
        run: ./gradlew clean test -Pprofile=prod

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Configure Docker to use Google Cloud CLI
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -f Dockerfile -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Tag and Push 'latest' Image
        run: |
          docker tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Instance Group
        run: |
          SOURCE_TEMPLATE_URL=$(gcloud compute instance-groups managed describe ${{ env.INSTANCE_GROUP_NAME }} --region=${{ env.GAR_LOCATION }} --format='value(instanceTemplate)')
          SOURCE_TEMPLATE_NAME=$(basename "$SOURCE_TEMPLATE_URL")

          NEW_TEMPLATE_NAME="shareme-backend-template-$(echo ${{ github.sha }} | cut -c1-12)"

          CONTAINER_SPEC=$(gcloud compute instance-templates describe $SOURCE_TEMPLATE_NAME --region=${{ env.GAR_LOCATION }} --format='value(properties.metadata.items.filter(key:gce-container-declaration).extract(value))')
          NEW_CONTAINER_SPEC=$(echo "$CONTAINER_SPEC" | sed "s|image: .*|image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|")

          echo "Source Template: $SOURCE_TEMPLATE_NAME"
          echo "New Template: $NEW_TEMPLATE_NAME"

          gcloud compute instance-templates create "$NEW_TEMPLATE_NAME" \
            --project=${{ env.PROJECT_ID }} \
            --source-instance-template=$SOURCE_TEMPLATE_NAME \
            --region=${{ env.GAR_LOCATION }} \
            --metadata=gce-container-declaration="$NEW_CONTAINER_SPEC"

          gcloud compute instance-groups managed rolling-action start-update ${{ env.INSTANCE_GROUP_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --version=template="$NEW_TEMPLATE_NAME" \
            --region=${{ env.GAR_LOCATION }} \
            --max-unavailable=0 \
            --max-surge=3

      - name: Discord Notification (Success)
        if: success()
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: 'GCP Deploy Bot'
          avatarUrl: 'https://avatars.githubusercontent.com/u/9919?s=200&v=4'
          severity: info
          title: '✅ Spring 애플리케이션 배포 성공!'
          description: '서버 롤링 업데이트가 시작되었습니다.'
          details: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

      - name: Discord Notification (Failure)
        if: failure()
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: 'GCP Deploy Bot'
          avatarUrl: 'https://avatars.githubusercontent.com/u/9919?s=200&v=4'
          severity: error
          title: '❌ Spring 애플리케이션 배포 실패!'
          description: '배포 과정 중 오류가 발생했습니다.'
          details: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
