on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: repository 로드
        uses: actions/checkout@v4

      - name: 카카오 설정 로드
        run: echo "${{ secrets.KAKAO_PROPERTIES }}" > ./src/main/resources/application-kakao.properties

      - name: db 설정 로드
        run: echo "${{ secrets.PROD_PROPERTIES }}" > ./src/main/resources/application-prod.properties

      - name: 테스트 및 빌드
        run: ./gradlew clean build -Pprofile=prod

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: project.jar
          target: "~/backend/new"

      - name: SSH 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo rm -rf ~/backend/current
            mkdir -p ~/backend/current
            mv ~/backend/new/project.jar ~/backend/current/project.jar
            cd ~/backend/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar --server.port=8080 --spring.profiles.active=prod > ./output.log 2>&1 &
            sudo rm -rf ~/backend/new
